### ISSUE TITLE
Very slow compilation (MSCV 12 up4 64bits)

### ISSUE THREAD

**Issue by DrSParis** [svgpp/svgpp#33]
Hello,

I am trying to use your library to load some SVG files under QT and post process them.

The compilation is terribly slow.
I mean I only include your main "svgpp/svgpp.hpp" in a single cpp file, where I bind everything into a Qobject, and that file takes something like 3 minutes to compile (Debug mode).
Removing your dependencies, it only takes 2-3 seconds.

Do you have any idea why it would be so slow?
After compilation everything looks fine, and I can execute my code.

**Comment by svgpp** [comment]
Hi,

I do have an idea why it is so slow, but don't have an idea how to make compilation faster in the general case. The reason is a very large number of template methods and functions instantiations (. 
You may try to isolate SVG++ usage to separate .cpp file, passing values received from SVG++ to some interface via virtual methods. This .cpp should be pretty stable and doesn't need frequent rebuilds, you may even put it in its own static library.
If you have hierarchy of context classes you may get additional reduce in compilation time if explicitly specify corresponding Event Policy with base class (by default it is specialized for each context type used), as in svgpp_agg_render:
svgpp::transform_events_policy<svgpp::policy::transform_events::forward_to_method<Transformable> >, // Same as default, but less instantiations
svgpp::path_events_policy<svgpp::policy::path_events::forward_to_method<Path> >, // Same as default, but less instantiations
svgpp::error_policy<svgpp::policy::error::default_policy<Stylable> >, // Type of context isn't used

**Comment by DrSParis** [comment]
Yes you are certainly right about the number of template instantiations.
MSVC is really poor at handling that.

I just find it strange as most of my code is template base (95% I would say) and it takes a lot less to compile. Nevertheless I make a smaller use of tags than you are, so perhaps that combined to a lot of Boost MPL usage makes the compiler crazy... 

I checked the cl process when it compiles, and it uses up to 2GB of ram during the process. It looks like it is over specializing things and developing template specialization branches too much isn't it? The thing is that we don't really have tools to benchmark the compiler and optimize compilation... or just find if something is going wrong with template specs.

As for isolating svgpp in a single cpp file, this is the way I did it. It is that single file with almost no other dependency (but some logging in std::cerr and some QT objects) that takes ages to compile (~ 3 minutes for a single file, where the most complex of my own code takes ~15secs).

**Comment by svgpp** [comment]
I can just agree with you:
1. MSVC isn't so bad, but Clang compiles svgpp code faster.
2. There is no good enough tool to profile template instantiations. I've used symbol maps from linker and from debug information but didn't find anything obviously excessive.
3. In a way SVG++ handles SVG, number of templates is proportional to the product of elements number and attributes number and it is a large number. Add here MPL collections and you get what you get.
4. I will try Spirit 3 some day. It is promised to be lighter for the compiler. We'll see.

**Comment by svgpp** [comment]
Some [workaround](http://svgpp.org/faq.html#compiler-is-out-of-memory-or-compilation-takes-too-long) was introduced in SVG++ 1.1. I can roughly estimate it as 2 times reduction in time and memory during compilation by Visual C++.
