### ISSUE TITLE
I can not use this on VS2015

### ISSUE THREAD

**Issue by Fogrunner** [svgpp/svgpp#44]
Hello. thank you for making good libs. Unfortunately, i  have faced a problem when i use it. 

My problem is like below :

I tried to use it on VS 2015. and i just added the libs at 'Additional Including folder'

and then i add ` "#include <svgpp/svgpp.h>"` to my cpp files.

When i tried to build it, i could see a lot of errors. 

The errors lists pointed to the 123 line at 'enumerate_literal_value.inc' file. 

> SVGPP_ON_VALUE(small)   // Error on Windows may be caused by "small" macro in RpcNdr.h 

The source code has already been marked that it will go to error. 

How can i do to use it? 

I worked with VS2015 and MFC.

**Comment by Fogrunner** [comment]
Already defined macros cause the errors. 

#undef small
#undef min
#undef max

i put above on stdafx.h

Additionally,  `"strerror"` function made error.

I have changed it to strerror_s.

**Comment by svgpp** [comment]
Thank you for the report. It is usually better to have NOMINMAX defined in VS project to enable correct std::min/max instead of ancient VC macros.
"#undef small" ahead of "#include <svgpp/svgpp.h>" also looks like pretty viable solution, probably I should extend comment in this line.
What is the problem with "strerror"? Where it is used in svgpp? Could you please copy all lines of error message here?
Is it all problems you have compiling svgpp so far?

**Comment by Fogrunner** [comment]
I was confused. It was error of Booster library. 

`errinfo_errno.hpp`  file made the error after including `svgpp.`

error C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\string.h(178): note: see declaration of 'strerror'
