### ISSUE TITLE
Unknown attribute

### ISSUE THREAD

**Issue by petrdd** [svgpp/svgpp#54]
How do I skip traversing of unknown attributes? It throws an exception and do not continue in parsing.

**Comment by svgpp** [comment]
Unknown attribute is an error according to [SVG Spec](https://www.w3.org/TR/SVG/implnote.html#ErrorProcessing) and rendering shall be stopped when it is encountered.
But if you want to ignore it anyway you may pass your own [Error Policy](http://svgpp.org/error.html) inherited from `policy::error::raise_exception` and override `unknown_attribute` function so that it will return `true` (ignore error).
