### ISSUE TITLE
Long compilation times and large files when compiling with clang and cmake

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [svgpp/svgpp#57]
I'm compiling the render demo with cmake and clang, and everytime I make changes the compilation can take several minutes. Also, I'm using CLion as my IDE, and for every update that I make to cmake I have to wait minutes for the symbols to be generated.

Another problem that I noticed, is that the object files that are being generated are really big. `svgpp_parser_impl.cpp.o` for instance is more than 50 MB. Is this normal? Any ideas of what could be causing long compilation times and large files? I know that templates are heavily used. 

It's getting to the point were I will not be able to use svgpp for the only reason that I can't wait this much time everytime that I make changes, and I also can't use such large executables in my project.

**Comment by svgpp** [comment]
Have you checked [this](http://svgpp.org/faq.html#compiler-is-out-of-memory-or-compilation-takes-too-long) article?
Recommended solution for long compilation time is to move code that uses svgpp to parse SVG into separate static library (or just .cpp) file with relatively stable virtual interfaces. So that the frequently changed code that uses parsing output is separated from svgpp.
Object file size isn't actually a problem. Executable of svgpp demo is roughly 1 Mb (depending on platform, compilation flags etc). Object and symbol files are large but it hardly can affect user.
