### ISSUE TITLE
SAX handling

### ISSUE THREAD

**Issue by abergmeier** [svgpp/svgpp#67]
I am wondering how to use svgpp without a DOM. Building a DOM might be unacceptable for large SVGs.
So I would use e.g. `libxml2`. But I cannot find a way other than `document_traversal` to load the xml.

**Comment by svgpp** [comment]
I had SAX in mind when designing SVG++. Interaction between SVG++ and XML parser is performed by means of so called [XML Policy](http://svgpp.org/overview.html#xml-parser). 
You may use [RapidXML NS policy](https://github.com/svgpp/svgpp/blob/master/include/svgpp/policy/xml/rapidxml_ns.hpp) as a sample (or others in the same directory). In brief, you should provide `element_iterator` and `attribute_iterator` specializations in `svgpp::policy::xml` namespace for the classes that will be used as wrappers XML element and XML attribute wrappers for your XML parser. There is no random access in XML policy interfaces so they should be suitable for SAX parser.

**Comment by abergmeier** [comment]
> I had SAX in mind when designing SVG++

Can you elaborate on that? From what I saw in policies, the policies themselves drive the processing via iterators. At least for _libxml2_ this is somewhat counter-intuitive, since _libxml2_ drives the (SAX) processing.
While I probably can make it work it seems to at least require 2 threads and synchronization on top to get the 2 drivers together.

**Comment by svgpp** [comment]
Good point. You may use [Boost.Coroutine](http://www.boost.org/doc/libs/1_66_0/libs/coroutine2/doc/html/index.html) library to invert SAX parser flow from event based to iterator-like.
On the second thought, using SAX parser has other disadvantages when compared to DOM. There are a number of cases when SVG elements reference each other by id (<use>, markers, clipping, masking etc.). When DOM is available we can just seach for XML element and parse it like if it was inserted in the referencing place. When using single-pass parser we'll have to store each element in internal structures (SVG DOM) so that we'll be able to process it when reference will be encountered. In other words we may use XML DOM instead of SVG DOM in some cases, but if we don't have XML DOM SVG DOM is essential. So there may be no memory gain using SAX parser.

**Comment by abergmeier** [comment]
That is what I feared. Since I really do not want to impose threading for such an easy task, I'll have a look whether I can implement an alternative to `document_traversal`.

**Comment by svgpp** [comment]
But why not coroutines?
Recursive SAX parsing is even used among the first [samples](http://www.boost.org/doc/libs/1_66_0/libs/coroutine/doc/html/coroutine/motivation.html#coroutine.motivation.recursive_sax_parsing) for the library.

**Comment by abergmeier** [comment]
> But why not coroutines?

Interesting question.
I do not have any experiences with coroutines to have any idea, how this would work.
And as usual boosts' examples are not self explanatory either :(
